### ISSUE TITLE
Fix page transitions

### ISSUE THREAD

**Issue by dptty** [roopemerikukka/yfd-website#90]
- [x] Fix flashes related to page transitions
- [x] Use next link in footer instead of plain links 
- [x] Add loading indicator
- [x] Tweak transitions
- [x] Page scrolls to top when Link is clicked. See monkeyPatchScrolling property?

**Comment by sarukuku** [comment]
At least in footer the links need to be changed from normal link to next link.

**Comment by sarukuku** [comment]
@dptty I fixed the footer links. Will you look at the page transitions or should I? There's already a PR open where we can push rest of the fixes related to this.

**Comment by dptty** [comment]
I'll give the page transitions a go tonight!
